#ifndef APP_USB_MUX_DEV_BOARD_CAPS_H
#define APP_USB_MUX_DEV_BOARD_CAPS_H

#define APP_USB_MAX_FRAME_LEN 512U
#define APP_UART_PORT_COUNT   4U
#define APP_BLE_MAX_LINKS     3U
#define APP_CAP_NET_RESERVED  1U

#endif
